Support posting dynamically generated streams
DarkWanderer/ClickHouse.Client pull request #479
Opened 2024-05-15 12:30 UTC by qed-

As described in #143, this allows large stream payloads to be written without having to materialize them up front, e.g. when uploading a huge file.

2024-06-17 13:57 UTC, qed- commented
@DarkWanderer would you consider merging this PR? Happy to make changes if you have any feedback.

2024-06-18 21:05 UTC, DarkWanderer commented
Hi. Will take a look this week

2024-06-24 14:31 UTC, DarkWanderer requested changes

2024-06-24 14:31 UTC, DarkWanderer commented on ClickHouse.Client/ADO/ClickHouseConnection.cs
> +    public Task PostStreamAsync(string sql, Stream data, bool isCompressed, CancellationToken token)
This breaks public interface - even though it's experimental. 
While I understand adding extra `await` introduces additional state machine, I feel it's not warranted to break it in this case

2024-06-24 14:31 UTC, DarkWanderer commented on ClickHouse.Client/ADO/ClickHouseConnection.cs
> +    public Task PostStreamAsync(string sql, Func<Stream, CancellationToken, Task> callback, bool isCompressed, CancellationToken token)
Same note about `async`/`await` - while this is a new function, it is worth maintaining consistency

2024-06-25 14:51 UTC, DarkWanderer approved these changes

2024-06-25 14:51 UTC, merged

2024-06-25 14:51 UTC, DarkWanderer commented
Looks good to me, thank you for your contribution!